// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import SakeAutocompleteController from "./sake_autocomplete_controller"
application.register("sake-autocomplete", SakeAutocompleteController)

import BreweryAutocompleteController from "./brewery_autocomplete_controller"
application.register("brewery-autocomplete", BreweryAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
